#!/bin/env python3

import random as rand
import mazes as m
import mazeFunctions as mf


chosen_maze = 0

maze_string = m.maze_char[chosen_maze]
matrix = m.maze_matrix[chosen_maze]
#print(maze_string)
#print(matrix)

cur_x,cur_y = mf.getInicialState(chosen_maze)

maze_string,matrix = mf.replace_char(maze_string,matrix,cur_x,cur_y)

loop = 0
while(loop < 1000):
    possibilities = mf.sucessor(chosen_maze,cur_x,cur_y)
    choice = rand.choice(possibilities)
    cur_x = choice[0]
    cur_y = choice[1]
    maze_string = mf.replace_char(maze_string,'▣',cur_x,cur_y)
    if mf.objetivo(chosen_maze,cur_x,cur_y): exit(1)
    loop = loop + 1
